version: "3.9"

services:
  app:
    build: .
    volumes:
      - ..:/workspace
    ports:
      - "8080:80"
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:11
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mport
      MYSQL_USER: mport
      MYSQL_PASSWORD: Mport@2026
    ports:
      - "3306:3306"
